import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { requireAdmin, isAuthError } from "@/lib/auth";
import { saveLibraryRules } from "@/lib/libraryRules";
import { replaceSystemHealthState } from "@/lib/systemHealth";

export const dynamic = "force-dynamic";

export async function POST(req: NextRequest) {
    const auth = await requireAdmin();
    if (isAuthError(auth)) return auth;

    try {
        const body = await req.json();

        if (!body || body.version !== "1.0" || !body.data) {
            return NextResponse.json({ error: "Invalid backup file format. Expected version 1.0 JSON generated by JellyTulli." }, { status: 400 });
        }

        const { users, media, playbackHistory, telemetryEvents, settings, libraryRules, systemHealth } = body.data;

        // Restore BigInt fields that were serialized as strings during export
        if (media && Array.isArray(media)) {
            for (const m of media) {
                if (m.durationMs !== undefined && m.durationMs !== null) {
                    m.durationMs = BigInt(m.durationMs);
                }
            }
        }
        if (playbackHistory && Array.isArray(playbackHistory)) {
            for (const h of playbackHistory) {
                // Convert date strings back to Date objects for Prisma
                if (h.startedAt && typeof h.startedAt === 'string') h.startedAt = new Date(h.startedAt);
                if (h.endedAt && typeof h.endedAt === 'string') h.endedAt = new Date(h.endedAt);
            }
        }
        if (telemetryEvents && Array.isArray(telemetryEvents)) {
            for (const e of telemetryEvents) {
                if (e.positionMs !== undefined && e.positionMs !== null) {
                    e.positionMs = BigInt(e.positionMs);
                }
                if (e.createdAt && typeof e.createdAt === 'string') e.createdAt = new Date(e.createdAt);
            }
        }

        // Perform atomic restore transaction
        await prisma.$transaction(async (tx) => {
            // 1. Clear current database completely (Volatile first, then records)
            await tx.activeStream.deleteMany();
            await tx.playbackHistory.deleteMany();
            await tx.media.deleteMany();
            await tx.user.deleteMany();
            await tx.systemHealthEvent.deleteMany();
            await tx.systemHealthState.deleteMany();
            await tx.globalSettings.deleteMany();

            // 2. Insert new records from JSON
            if (users && users.length > 0) {
                await tx.user.createMany({ data: users });
            }
            if (media && media.length > 0) {
                await tx.media.createMany({ data: media });
            }
            if (playbackHistory && playbackHistory.length > 0) {
                await tx.playbackHistory.createMany({ data: playbackHistory });
            }
            if (telemetryEvents && telemetryEvents.length > 0) {
                await (tx as any).telemetryEvent.createMany({ data: telemetryEvents });
            }
            if (settings) {
                // Strip legacy jellyfinUrl/jellyfinApiKey fields (now env vars)
                const { jellyfinUrl, jellyfinApiKey, ...cleanSettings } = settings as any;
                await tx.globalSettings.create({
                    data: {
                        id: cleanSettings.id || "global",
                        discordWebhookUrl: cleanSettings.discordWebhookUrl ?? null,
                        discordAlertCondition: cleanSettings.discordAlertCondition ?? "ALL",
                        discordAlertsEnabled: cleanSettings.discordAlertsEnabled ?? false,
                        excludedLibraries: cleanSettings.excludedLibraries ?? [],
                        monitorIntervalActive: cleanSettings.monitorIntervalActive ?? 1000,
                        monitorIntervalIdle: cleanSettings.monitorIntervalIdle ?? 5000,
                        syncCronHour: cleanSettings.syncCronHour ?? 3,
                        syncCronMinute: cleanSettings.syncCronMinute ?? 0,
                        backupCronHour: cleanSettings.backupCronHour ?? 3,
                        backupCronMinute: cleanSettings.backupCronMinute ?? 30,
                        defaultLocale: cleanSettings.defaultLocale ?? "fr",
                        timeFormat: cleanSettings.timeFormat ?? "24h",
                    }
                });
            }
        }, {
            timeout: 60000 // Give it 60 seconds if the DB is massive
        });

        if (libraryRules) {
            await saveLibraryRules(libraryRules);
        }
        if (systemHealth) {
            await replaceSystemHealthState(systemHealth);
        }

        return NextResponse.json({ success: true }, { status: 200 });

    } catch (e: any) {
        console.error("[BackupImport] Restauration failed:", e);
        return NextResponse.json({ error: e.message || "Failed to restore backup" }, { status: 500 });
    }
}
