import { NextRequest, NextResponse } from "next/server";
import { randomUUID } from "crypto";
import prisma from "@/lib/prisma";
import { requireAdmin, isAuthError } from "@/lib/auth";
// No rules
import { replaceSystemHealthState } from "@/lib/systemHealth";
import { getMasterServerIdentityFromEnv } from "@/lib/serverRegistry";

export const dynamic = "force-dynamic";

export async function POST(req: NextRequest) {
    const auth = await requireAdmin();
    if (isAuthError(auth)) return auth;

    try {
        const body = await req.json();

        if (!body || body.version !== "1.0" || !body.data) {
            return NextResponse.json({ error: "Invalid backup file format. Expected version 1.0 JSON generated by JellyTrack." }, { status: 400 });
        }

        const { servers, users, media, playbackHistory, telemetryEvents, settings, systemHealth } = body.data;

        const masterIdentity = getMasterServerIdentityFromEnv();
        const normalizedServers = Array.isArray(servers) && servers.length > 0
            ? servers.map((s: Record<string, unknown>, index: number) => ({
                id: (typeof s.id === "string" && s.id) ? s.id : randomUUID(),
                jellyfinServerId: (typeof s.jellyfinServerId === "string" && s.jellyfinServerId)
                    ? s.jellyfinServerId
                    : `imported-server-${index + 1}`,
                name: (typeof s.name === "string" && s.name) ? s.name : `Imported Server ${index + 1}`,
                url: (typeof s.url === "string" && s.url) ? s.url : masterIdentity.url,
                isActive: typeof s.isActive === "boolean" ? s.isActive : true,
                createdAt: s.createdAt ? new Date(String(s.createdAt)) : new Date(),
                updatedAt: s.updatedAt ? new Date(String(s.updatedAt)) : new Date(),
            }))
            : [{
                id: randomUUID(),
                jellyfinServerId: masterIdentity.jellyfinServerId,
                name: masterIdentity.name,
                url: masterIdentity.url,
                isActive: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            }];

        const defaultServerId = normalizedServers[0].id;

        // Restore BigInt fields that were serialized as strings during export
        if (media && Array.isArray(media)) {
            for (const m of media) {
                if (m.durationMs !== undefined && m.durationMs !== null) {
                    m.durationMs = BigInt(m.durationMs);
                }
            }
        }
        if (playbackHistory && Array.isArray(playbackHistory)) {
            for (const h of playbackHistory) {
                // Convert date strings back to Date objects for Prisma
                if (h.startedAt && typeof h.startedAt === 'string') h.startedAt = new Date(h.startedAt);
                if (h.endedAt && typeof h.endedAt === 'string') h.endedAt = new Date(h.endedAt);
            }
        }
        if (telemetryEvents && Array.isArray(telemetryEvents)) {
            for (const e of telemetryEvents) {
                if (e.positionMs !== undefined && e.positionMs !== null) {
                    e.positionMs = BigInt(e.positionMs);
                }
                if (e.createdAt && typeof e.createdAt === 'string') e.createdAt = new Date(e.createdAt);
            }
        }

        // Perform atomic restore transaction
        await prisma.$transaction(async (tx) => {
            // 1. Clear current database completely (Volatile first, then records)
            await tx.activeStream.deleteMany();
            await tx.playbackHistory.deleteMany();
            await tx.media.deleteMany();
            await tx.user.deleteMany();
            await tx.server.deleteMany();
            await tx.systemHealthEvent.deleteMany();
            await tx.systemHealthState.deleteMany();
            await tx.globalSettings.deleteMany();

            // 2. Insert new records from JSON
            if (normalizedServers.length > 0) {
                await tx.server.createMany({ data: normalizedServers });
            }

            if (users && users.length > 0) {
                const usersToInsert = users.map((u: Record<string, unknown>) => ({
                    ...u,
                    serverId: (typeof u.serverId === "string" && u.serverId) ? u.serverId : defaultServerId,
                }));
                await tx.user.createMany({ data: usersToInsert });
            }
            if (media && media.length > 0) {
                const mediaToInsert = media.map((m: Record<string, unknown>) => ({
                    ...m,
                    serverId: (typeof m.serverId === "string" && m.serverId) ? m.serverId : defaultServerId,
                }));
                await tx.media.createMany({ data: mediaToInsert });
            }

            const playbackToInsert: Record<string, unknown>[] = Array.isArray(playbackHistory)
                ? playbackHistory.map((h: Record<string, unknown>) => ({
                    ...h,
                    serverId: (typeof h.serverId === "string" && h.serverId) ? h.serverId : defaultServerId,
                }))
                : [];

            if (playbackHistory && playbackHistory.length > 0) {
                await tx.playbackHistory.createMany({ data: playbackToInsert as any });
            }

            const playbackServerMap = new Map<string, string>();
            for (const entry of playbackToInsert) {
                const playbackId = typeof entry["id"] === "string" ? entry["id"] : null;
                const playbackServerId = typeof entry["serverId"] === "string" ? entry["serverId"] : defaultServerId;
                if (playbackId) {
                    playbackServerMap.set(playbackId, playbackServerId);
                }
            }

            if (telemetryEvents && telemetryEvents.length > 0) {
                const telemetryToInsert = telemetryEvents.map((e: Record<string, unknown>) => ({
                    ...e,
                    serverId: (typeof e.serverId === "string" && e.serverId)
                        ? e.serverId
                        : playbackServerMap.get(String(e.playbackId || "")) || defaultServerId,
                }));
                await tx.telemetryEvent.createMany({ data: telemetryToInsert });
            }
            if (settings) {
                // Strip legacy jellyfinUrl/jellyfinApiKey fields (now env vars)
                const cs = settings as Record<string, unknown>;
                await tx.globalSettings.create({
                    data: {
                        id: (cs['id'] as string) || "global",
                        discordWebhookUrl: (cs['discordWebhookUrl'] as string) ?? null,
                        discordAlertCondition: (cs['discordAlertCondition'] as string) ?? "ALL",
                        discordAlertsEnabled: (cs['discordAlertsEnabled'] as boolean) ?? false,
                        excludedLibraries: (cs['excludedLibraries'] as string[]) ?? [],
                        syncCronHour: (cs['syncCronHour'] as number) ?? 3,
                        syncCronMinute: (cs['syncCronMinute'] as number) ?? 0,
                        backupCronHour: (cs['backupCronHour'] as number) ?? 3,
                        backupCronMinute: (cs['backupCronMinute'] as number) ?? 30,
                        defaultLocale: (cs['defaultLocale'] as string) ?? "fr",
                        timeFormat: (cs['timeFormat'] as string) ?? "24h",
                    }
                });
            }
        }, {
            timeout: 60000 // Give it 60 seconds if the DB is massive
        });

        // Skip library rules
        if (systemHealth) {
            await replaceSystemHealthState(systemHealth);
        }

        return NextResponse.json({ success: true }, { status: 200 });

    } catch (e: unknown) {
        const msg = e instanceof Error ? e.message : String(e);
        console.error("[BackupImport] Restauration failed:", e);
        return NextResponse.json({ error: msg || "Failed to restore backup" }, { status: 500 });
    }
}
