import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import prisma from "@/lib/prisma";

export const dynamic = "force-dynamic";

export async function POST(req: NextRequest) {
    const session = await getServerSession(authOptions);
    if (!session) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    try {
        const body = await req.json();

        if (!body || body.version !== "1.0" || !body.data) {
            return NextResponse.json({ error: "Invalid backup file format. Expected version 1.0 JSON generated by JellyTulli." }, { status: 400 });
        }

        const { users, media, playbackHistory, settings } = body.data;

        // Restore BigInt fields that were serialized as strings during export
        if (media && Array.isArray(media)) {
            for (const m of media) {
                if (m.durationMs !== undefined && m.durationMs !== null) {
                    m.durationMs = BigInt(m.durationMs);
                }
            }
        }
        if (playbackHistory && Array.isArray(playbackHistory)) {
            for (const h of playbackHistory) {
                // Convert date strings back to Date objects for Prisma
                if (h.startedAt && typeof h.startedAt === 'string') h.startedAt = new Date(h.startedAt);
                if (h.endedAt && typeof h.endedAt === 'string') h.endedAt = new Date(h.endedAt);
            }
        }

        // Perform atomic restore transaction
        await prisma.$transaction(async (tx) => {
            // 1. Clear current database completely (Volatile first, then records)
            await tx.activeStream.deleteMany();
            await tx.playbackHistory.deleteMany();
            await tx.media.deleteMany();
            await tx.user.deleteMany();
            await tx.globalSettings.deleteMany();

            // 2. Insert new records from JSON
            if (users && users.length > 0) {
                await tx.user.createMany({ data: users });
            }
            if (media && media.length > 0) {
                await tx.media.createMany({ data: media });
            }
            if (playbackHistory && playbackHistory.length > 0) {
                await tx.playbackHistory.createMany({ data: playbackHistory });
            }
            if (settings) {
                await tx.globalSettings.create({ data: settings });
            }
        }, {
            timeout: 60000 // Give it 60 seconds if the DB is massive
        });

        return NextResponse.json({ success: true }, { status: 200 });

    } catch (e: any) {
        console.error("[BackupImport] Restauration failed:", e);
        return NextResponse.json({ error: e.message || "Failed to restore backup" }, { status: 500 });
    }
}
